http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

# Performance settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
monitoring.enabled: false

# Queue settings
queue.type: memory

# Log level
log.level: info 